version: "3.7"

services:
  backend:
    container_name: backend
    build: 
      context: ./backend
    depends_on:
      - postgres
    environment:
      HOST: 0.0.0.0
      PORT: 3333
      NODE_ENV: production
      APP_NAME: AdonisJs
      APP_URL: http://${HOST}:${PORT}
      APP_KEY: 2uhLYRemq1zM3qIBx2qcnIRSVyTSTcc2
      CACHE_VIEWS: 'false'
      DB_CONNECTION: pg
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: pass
      DB_DATABASE: db
      HASH_DRIVER: bcrypt
    ports:
      - "3333:3333"

  postgres:
    image: postgres:alpine
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    environment:
      VUE_APP_MOCK: 'false'
      VUE_APP_API_URL: 'http://0.0.0.0:3333'
    ports:
      - '8080:80'
